In [1]:
import pandas as pd
df=pd.read_csv('train.csv', encoding='latin-1')

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics

In [3]:
df.head()

,ID,DiagnosticICD10Code,SurgeryGroup,AnesthesiaType,SurgeryName,Age,Sex,Service,DoctorID,AnaesthetistID,ElapsedTime(second)
0,1829,{'L05'},{'C'},Spinal Anestezi,Pilonidal kist,26,MALE,GENEL CERRAH? SERV?S?,5,13,6333
1,1104,{'N20.1'},{'C'},Spinal Anestezi,NaN,24,MALE,ÜROLOJ? SERV?S?,15,3,2972
2,1850,{'K80.8'},{'B'},Genel Anestezi,"Kolelitiazis, di?er",38,MALE,GENEL CERRAH? SERV?S?,36,14,4647
3,1059,"{nan, 'M51.1'}","{0, 'B'}",Genel Anestezi,Lumbar ve di?er intervertebral disk bozuklukla...,41,FEMALE,ORTOPED? SERV?S?,42,6,4871
4,608,"{'M51.1', nan, 'M48.0'}","{0, 'B', 'C', 'D', 'A3'}",Genel Anestezi,Lumbar ve di?er intervertebral disk bozuklukla...,49,FEMALE,ORTOPED? SERV?S?,42,9,9046

In [4]:
df.shape

(2822, 11)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2822 entries, 0 to 2821
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   2822 non-null   int64
 1   DiagnosticICD10Code  2601 non-null   object
 2   SurgeryGroup         2822 non-null   object
 3   AnesthesiaType       2601 non-null   object
 4   SurgeryName          2447 non-null   object
 5   Age                  2822 non-null   int64
 6   Sex                  2822 non-null   object
 7   Service              2822 non-null   object
 8   DoctorID             2822 non-null   int64
 9   AnaesthetistID       2822 non-null   int64
 10  ElapsedTime(second)  2822 non-null   int64
dtypes: int64(5), object(6)
memory usage: 242.6+ KB

In [6]:
# Categorical Features: DiagnosticICD10Code, SurgeryGroup, AnesthesiaType, SurgeryName, Sex, Service, DoctorID, AnaesthetistID
df.isnull().sum()

ID                       0
DiagnosticICD10Code    221
SurgeryGroup             0
AnesthesiaType         221
SurgeryName            375
Age                      0
Sex                      0
Service                  0
DoctorID                 0
AnaesthetistID           0
ElapsedTime(second)      0
dtype: int64

In [7]:
df= df.dropna(axis=0)

In [8]:
df.isnull().sum()

ID                     0
DiagnosticICD10Code    0
SurgeryGroup           0
AnesthesiaType         0
SurgeryName            0
Age                    0
Sex                    0
Service                0
DoctorID               0
AnaesthetistID         0
ElapsedTime(second)    0
dtype: int64

In [9]:
df.shape

(2264, 11)

In [10]:
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Certain infectious and parasitic diseases' if "'A" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Certain infectious and parasitic diseases' if "'B" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Neoplasms' if "'C" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Neoplasms' if "'D0"in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Neoplasms' if "'D1"in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Neoplasms' if "'D2"in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Neoplasms' if "'D3"in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Neoplasms' if "'D4"in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism' if "'D5" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism' if "'D6" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism' if "'D7" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism' if "'D8" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism' if "'D9" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Endocrine, nutritional and metabolic diseases' if "'E" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Mental, Behavioral and Neurodevelopmental disorders' if "'F" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Diseases of the nervous system' if "'G" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Diseases of the eye and adnexa' if "'H0" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Diseases of the eye and adnexa' if "'H1" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Diseases of the eye and adnexa' if "'H2" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Diseases of the eye and adnexa' if "'H3" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Diseases of the eye and adnexa' if "'H4" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Diseases of the eye and adnexa' if "'H5" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Diseases of the ear and mastoid process' if "'H6" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Diseases of the ear and mastoid process' if "'H7" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Diseases of the ear and mastoid process' if "'H8" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Diseases of the ear and mastoid process' if "'H9" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Diseases of the circulatory systems' if "'I" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Diseases of the respiratory system' if "'J" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Diseases of the digestive system' if "'K" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Diseases of the skin and subcutaneous tissue' if "'L" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Diseases of the musculoskeletal system and connective tissue' if "'M" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Diseases of the genitourinary system' if "'N" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Pregnancy, childbirth and the puerperium' if "'O" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Certain conditions originating in the perinatal period' if "'P" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Congenital malformations, deformations and chromosomal abnormalities' if "'Q" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Symptoms, signs and abnormal clinical and laboratory findings, not elsewhere classified' if "'R" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Injury, poisoning and certain other consequences of external causes' if "'S" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Injury, poisoning and certain other consequences of external causes' if "'T" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Codes for special purposes' if "'U" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'External causes of morbidity' if "'V" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'External causes of morbidity' if "'W" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'External causes of morbidity' if "'Y" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Factors influencing health status and contact with health services' if "'Z" in x else x)

In [11]:
df.head()

,ID,DiagnosticICD10Code,SurgeryGroup,AnesthesiaType,SurgeryName,Age,Sex,Service,DoctorID,AnaesthetistID,ElapsedTime(second)
0,1829,Diseases of the skin and subcutaneous tissue,{'C'},Spinal Anestezi,Pilonidal kist,26,MALE,GENEL CERRAH? SERV?S?,5,13,6333
2,1850,Diseases of the digestive system,{'B'},Genel Anestezi,"Kolelitiazis, di?er",38,MALE,GENEL CERRAH? SERV?S?,36,14,4647
3,1059,Diseases of the musculoskeletal system and con...,"{0, 'B'}",Genel Anestezi,Lumbar ve di?er intervertebral disk bozuklukla...,41,FEMALE,ORTOPED? SERV?S?,42,6,4871
4,608,Diseases of the musculoskeletal system and con...,"{0, 'B', 'C', 'D', 'A3'}",Genel Anestezi,Lumbar ve di?er intervertebral disk bozuklukla...,49,FEMALE,ORTOPED? SERV?S?,42,9,9046
5,1895,Diseases of the musculoskeletal system and con...,"{'D', 'C'}",Genel Anestezi,Burnun kazan?lm?? deformitesi,33,MALE,PLAST?K CERRAH?,39,13,11146

In [12]:
df["DiagnosticICD10Code"].value_counts()

Diseases of the digestive system                                                                       726
Diseases of the circulatory systems                                                                    497
Diseases of the musculoskeletal system and connective tissue                                           336
Diseases of the genitourinary system                                                                   212
Diseases of the skin and subcutaneous tissue                                                           136
Diseases of the eye and adnexa                                                                          92
Diseases of the respiratory system                                                                      89
Injury, poisoning and certain other consequences of external causes                                     48
Factors influencing health status and contact with health services                                      44
Symptoms, signs and abnormal clinical and laboratory findings, not elsewhere classified                 23
Neoplasms                                                                                               19
Diseases of the nervous system                                                                           9
External causes of morbidity                                                                             8
Diseases of the ear and mastoid process                                                                  6
Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism      5
Endocrine, nutritional and metabolic diseases                                                            4
Certain infectious and parasitic diseases                                                                4
Congenital malformations, deformations and chromosomal abnormalities                                     3
Pregnancy, childbirth and the puerperium                                                                 2
Mental, Behavioral and Neurodevelopmental disorders                                                      1
Name: DiagnosticICD10Code, dtype: int64

In [13]:
df['SurgeryGroup'] = df['SurgeryGroup'].apply(lambda x: "4000" if "A1" in x else x)
df['SurgeryGroup'] = df['SurgeryGroup'].apply(lambda x: "2500" if "A2" in x else x)
df['SurgeryGroup'] = df['SurgeryGroup'].apply(lambda x: "1250" if "A3" in x else x)
df['SurgeryGroup'] = df['SurgeryGroup'].apply(lambda x: "750" if "B" in x else x)
df['SurgeryGroup'] = df['SurgeryGroup'].apply(lambda x: "400" if "C" in x else x)
df['SurgeryGroup'] = df['SurgeryGroup'].apply(lambda x: "200" if "D" in x else x)
df['SurgeryGroup'] = df['SurgeryGroup'].apply(lambda x: "100" if "E" in x else x)
df['SurgeryGroup'] = df['SurgeryGroup'].apply(lambda x: "0" if "{0}" in x else x)

In [14]:
df.head()

,ID,DiagnosticICD10Code,SurgeryGroup,AnesthesiaType,SurgeryName,Age,Sex,Service,DoctorID,AnaesthetistID,ElapsedTime(second)
0,1829,Diseases of the skin and subcutaneous tissue,400,Spinal Anestezi,Pilonidal kist,26,MALE,GENEL CERRAH? SERV?S?,5,13,6333
2,1850,Diseases of the digestive system,750,Genel Anestezi,"Kolelitiazis, di?er",38,MALE,GENEL CERRAH? SERV?S?,36,14,4647
3,1059,Diseases of the musculoskeletal system and con...,750,Genel Anestezi,Lumbar ve di?er intervertebral disk bozuklukla...,41,FEMALE,ORTOPED? SERV?S?,42,6,4871
4,608,Diseases of the musculoskeletal system and con...,1250,Genel Anestezi,Lumbar ve di?er intervertebral disk bozuklukla...,49,FEMALE,ORTOPED? SERV?S?,42,9,9046
5,1895,Diseases of the musculoskeletal system and con...,400,Genel Anestezi,Burnun kazan?lm?? deformitesi,33,MALE,PLAST?K CERRAH?,39,13,11146

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2264 entries, 0 to 2600
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   2264 non-null   int64
 1   DiagnosticICD10Code  2264 non-null   object
 2   SurgeryGroup         2264 non-null   object
 3   AnesthesiaType       2264 non-null   object
 4   SurgeryName          2264 non-null   object
 5   Age                  2264 non-null   int64
 6   Sex                  2264 non-null   object
 7   Service              2264 non-null   object
 8   DoctorID             2264 non-null   int64
 9   AnaesthetistID       2264 non-null   int64
 10  ElapsedTime(second)  2264 non-null   int64
dtypes: int64(5), object(6)
memory usage: 212.2+ KB

In [16]:
df["SurgeryGroup"]=df["SurgeryGroup"].astype("int64")

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2264 entries, 0 to 2600
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   2264 non-null   int64
 1   DiagnosticICD10Code  2264 non-null   object
 2   SurgeryGroup         2264 non-null   int64
 3   AnesthesiaType       2264 non-null   object
 4   SurgeryName          2264 non-null   object
 5   Age                  2264 non-null   int64
 6   Sex                  2264 non-null   object
 7   Service              2264 non-null   object
 8   DoctorID             2264 non-null   int64
 9   AnaesthetistID       2264 non-null   int64
 10  ElapsedTime(second)  2264 non-null   int64
dtypes: int64(6), object(5)
memory usage: 212.2+ KB

In [18]:
df["Sex"].value_counts()

MALE      1224
FEMALE    1040
Name: Sex, dtype: int64

In [19]:
df["SurgeryGroup"].value_counts()

750     834
400     688
100     441
1250    136
200     118
0        45
2500      2
Name: SurgeryGroup, dtype: int64

In [20]:
df["AnesthesiaType"].value_counts()

Genel Anestezi                         921
Sedo Analjezi                          708
Spinal Anestezi                        553
Lokal Anestezi                          52
Rejyonel Sinir Blo?u                    14
Epidural ve Genel Anestezi               8
Epidural Anestezi                        2
Periferik Bloklar                        2
Spinal ve Genel Anestezi                 2
Seçilmemi?                               1
Periferik Bloklar ve Genel Anestezi      1
Name: AnesthesiaType, dtype: int64

In [21]:
df["SurgeryName"].value_counts()

Ülser veya enflamasyon olmadan alt ekstremitenin variköz venleri           370
Bilateral inguinal herni, obstrüksiyonsuz veya gangrensiz                  223
Kolelitiazis, di?er                                                        204
Lumbar ve di?er intervertebral disk bozukluklar?, radikülopati ile         106
Pilonidal kist                                                              78
                                                                          ...
Variköz venler, di?er yerlerin                                               1
Ulna ?aft? k?r???                                                            1
Ventral herni, gangrenli                                                     1
Ulnar sinir lezyonu                                                          1
Kabul edilebilir olmayan kozmetik görünüm için di?er plastik cerrahiler      1
Name: SurgeryName, Length: 230, dtype: int64

In [22]:
df["Service"].value_counts()

GENEL CERRAH? SERV?S?          833
KVC SERV?S?                    411
ORTOPED? SERV?S?               330
ÜROLOJ? SERV?S?                266
PLAST?K CERRAH?                109
KBB SERV?S?                     88
NÖRO??RÜRJ? SERV?S?             81
GÖZ HASTALIKLARI SERV?S?        78
KADIN DO?UM SERV?S?             38
GENEL KARMA CERRAH? SERV?S?     30
Name: Service, dtype: int64

In [23]:
df["DoctorID"].value_counts()

36    217
5     208
25    201
46    170
47    165
42    127
43    124
39     90
31     86
49     74
21     71
8      71
40     58
29     57
26     54
15     50
32     48
33     48
23     39
11     39
27     37
48     30
10     29
6      28
18     23
17     22
28     19
22     11
35     10
45     10
19      8
16      8
37      7
20      6
2       3
41      3
9       3
4       2
12      2
44      2
24      1
1       1
7       1
14      1
Name: DoctorID, dtype: int64

In [24]:
df["AnaesthetistID"].value_counts()

12    333
4     325
2     272
6     256
13    255
11    243
14    216
9      88
10     69
3      62
1      49
7      34
15     28
5      25
16      9
Name: AnaesthetistID, dtype: int64

In [25]:
df.head()

,ID,DiagnosticICD10Code,SurgeryGroup,AnesthesiaType,SurgeryName,Age,Sex,Service,DoctorID,AnaesthetistID,ElapsedTime(second)
0,1829,Diseases of the skin and subcutaneous tissue,400,Spinal Anestezi,Pilonidal kist,26,MALE,GENEL CERRAH? SERV?S?,5,13,6333
2,1850,Diseases of the digestive system,750,Genel Anestezi,"Kolelitiazis, di?er",38,MALE,GENEL CERRAH? SERV?S?,36,14,4647
3,1059,Diseases of the musculoskeletal system and con...,750,Genel Anestezi,Lumbar ve di?er intervertebral disk bozuklukla...,41,FEMALE,ORTOPED? SERV?S?,42,6,4871
4,608,Diseases of the musculoskeletal system and con...,1250,Genel Anestezi,Lumbar ve di?er intervertebral disk bozuklukla...,49,FEMALE,ORTOPED? SERV?S?,42,9,9046
5,1895,Diseases of the musculoskeletal system and con...,400,Genel Anestezi,Burnun kazan?lm?? deformitesi,33,MALE,PLAST?K CERRAH?,39,13,11146

In [26]:
from sklearn.preprocessing import LabelEncoder

In [27]:
encoder = LabelEncoder()

In [28]:
df["DiagnosticICD10Code"]=encoder.fit_transform(df["DiagnosticICD10Code"])
df["AnesthesiaType"]=encoder.fit_transform(df["AnesthesiaType"])
df["Sex"]=encoder.fit_transform(df["Sex"])
df["Service"]=encoder.fit_transform(df["Service"])
df["DoctorID"]=encoder.fit_transform(df["DoctorID"])
df["AnaesthetistID"]=encoder.fit_transform(df["AnaesthetistID"])

In [29]:
df.head()

,ID,DiagnosticICD10Code,SurgeryGroup,AnesthesiaType,SurgeryName,Age,Sex,Service,DoctorID,AnaesthetistID,ElapsedTime(second)
0,1829,11,400,9,Pilonidal kist,26,1,0,3,11,6333
2,1850,4,750,2,"Kolelitiazis, di?er",38,1,0,31,12,4647
3,1059,8,750,2,Lumbar ve di?er intervertebral disk bozuklukla...,41,0,7,36,5,4871
4,608,8,1250,2,Lumbar ve di?er intervertebral disk bozuklukla...,49,0,7,36,7,9046
5,1895,8,400,2,Burnun kazan?lm?? deformitesi,33,1,8,33,11,11146

In [30]:
x=df.drop(columns=["ID", "ElapsedTime(second)","SurgeryName"], axis=1)
y=df["ElapsedTime(second)"]

In [31]:
x.head()

,DiagnosticICD10Code,SurgeryGroup,AnesthesiaType,Age,Sex,Service,DoctorID,AnaesthetistID
0,11,400,9,26,1,0,3,11
2,4,750,2,38,1,0,31,12
3,8,750,2,41,0,7,36,5
4,8,1250,2,49,0,7,36,7
5,8,400,2,33,1,8,33,11

In [32]:
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.2, random_state=2)

In [33]:
reg=LinearRegression()

In [34]:
reg.fit(x_train, y_train)

LinearRegression()

In [35]:
reg.predict(x_test)

array([2594.44060679, 3141.73741606, 4781.23621305, 4601.31650409,
       2678.69373531, 5634.91861433, 4445.14367752, 5589.97956991,
       2332.1243979 , 4159.45370242, 6068.44796806, 4039.26473829,
       4037.59050117, 2878.93108927, 6236.20716631, 2551.06858835,
       5221.37086276, 4796.82048903, 5773.77080074, 2557.98866551,
       3297.01231265, 5315.02250375, 2776.52846677, 3126.37250525,
       2415.39565526, 6373.055153  , 2881.76171869, 2564.51401248,
       3230.62264892, 2762.36676189, 5327.25338033, 4011.00747562,
       5390.67904791, 3543.81869589, 2357.81396296, 7544.1512501 ,
       6297.99041196, 3809.50430628, 3888.59497775, 5300.6727374 ,
       8816.80224738, 7619.84973463, 2926.88368563, 4282.26330636,
       2896.03507575, 4103.50493754, 3179.79466475, 2468.44659663,
       4761.07348815, 5848.80453224, 5485.2624881 , 1844.92116696,
       9501.09735678, 2179.96282318, 5258.23835791, 2617.70469041,
       9078.27327208, 2779.13039014, 5901.09662919, 1848.40106202,
       5305.56650376, 4193.77489231, 3572.31159136, 7167.28937478,
       3678.03735404, 2182.68377002, 5774.78969282, 5005.25730174,
       4753.04688037, 2292.91481347, 2916.9072603 , 5628.54018524,
       6085.43180566, 3826.58938401, 2942.99841557, 5851.79112358,
       1993.12838143, 2461.66728782, 1839.70401026, 3924.88376308,
       4089.07066166, 3041.70979742, 5554.32760593, 5811.89544243,
       4130.23109627, 5468.15673445, 5372.78109617, 2430.50804183,
       2577.80900927, 3811.63199185, 5176.3677075 , 2587.55338256,
       2551.26235565, 9082.62179796, 9466.97340949, 3139.51569395,
       2262.5848149 , 4298.60653057, 2732.28425974, 2973.51276229,
       6069.41268849, 9506.20483089, 4087.34502981, 9083.41757726,
       5697.8969376 , 2627.67021948, 1031.59594192, 3305.54449222,
       2840.91865873, 4661.05739292, 4416.70507717, 1976.8948398 ,
       3056.2013185 , 5379.66445358, 5919.80894331, 7206.54626444,
       6405.49026468, 3499.03103661, 4756.72496227, 5237.99976284,
       6154.60839668, 2364.11880659, 4546.21065206, 2253.88776314,
       2699.12363175, 3298.4060348 , 4660.34534098, 2345.96121215,
       2253.48614948, 2856.31982906, 2862.88126619, 5801.88826888,
       4487.01287677, 6784.95109674, 4092.36639844, 6950.37437704,
       9101.59173034, 2489.14016077, 3809.01902349, 8756.23704372,
       4972.06328013, 4528.44942722, 2784.27598326, 3005.89558829,
       3447.11672099, 5861.07024689, 6207.94947852, 3565.92129282,
       5311.63277172, 8892.24508379, 3672.27273929, 8882.62643856,
       5681.26278936, 2622.3415896 , 5363.81508227, 3830.46096965,
       3263.76705965, 1777.30675149,  588.14671129, 4659.37687861,
       5899.92254117, 5221.22908462, 4246.08270068, 8532.91162566,
       4613.71538494, 3947.33942933, 5459.48787786, 3604.69805821,
       3971.92040677, 5631.11337192, 1944.93726219, 5714.184738  ,
       5030.88725618, 8417.95341161, 5932.16455742, 1764.26117385,
       5159.84631718, 4139.04905703, 3027.63695685, 5742.14215168,
       1712.64267665, 6188.63479099, 2733.15289055, 5838.27852879,
       1834.00723565, 3044.40088438, 7415.46901829, 6115.88534895,
       2880.66438183, 1923.59703161, 2157.46124556, 6036.47321626,
       6665.1790185 , 5577.42718953, 6879.97119105, 4743.87923025,
       3631.76561901, 2992.74716768, 2988.40318449, 2850.12582902,
       5089.09131646, 2297.03137341, 5531.9659075 , 3360.11390366,
       4192.91632265, 9408.10274137, 5846.68364947, 2529.97522459,
       2377.16438423, 2839.79435635, 5966.07354867, 2482.61647665,
       4945.22947155, 5801.63979633, 2069.27427477, 3543.05974766,
       7054.05400438, 6300.56463308, 2944.04929488, 6123.85491844,
       2885.99700422, 4943.05431331, 8878.22232473, 3706.2320499 ,
       1853.61821872, 2999.228259  , 6309.89373613, 2187.77467429,
       3918.6338179 , 5987.35437408, 6271.53167895, 3770.04430621,
       8789.94707031, 4207.44892097, 4887.88393405, 2563.71257576,
       2364.11880659, 4979.36041681, 3542.8520142 , 3326.94618664,
       6743.60713343, 5350.12955843, 1307.66727179, 4418.0075656 ,
       6424.47372964, 5666.66052718, 4439.89436993, 5215.50444042,
       2891.21771868, 6470.99956704, 6571.14147644, 3264.95884754,
       4177.60675417, 4053.44870904, 7339.77053375, 2812.18530462,
       5518.02150243, 8409.63500457, 4639.59561823, 4300.88337526,
       5508.81136382, 4779.42638551, 5070.48518993, 9101.59173034,
       5463.57557905, 2583.02616596, 3957.71331136, 4397.82297969,
       3592.37983141, 4238.30923981, 5908.79255837, 5255.58639577,
       6271.18044264, 4975.69033378, 4224.65123033, 6227.74055217,
       6860.92775403, 3961.9488148 , 5156.37173726, 5861.0314588 ,
       1438.14199411, 5571.72170944, 3970.14256452, 2282.66303419,
       6741.0349384 , 2946.04222807, 3083.77478866, 6277.88501777,
       2050.81977976, 5986.75277969, 5953.32511527, 6777.54794606,
       3386.4274317 , 2644.30537477, 3207.81035798, 2967.06040159,
       2274.76176172, 4045.87554334, 3064.13942204, 2358.21555318,
       6214.97014221, 3074.79582973, 3605.42540905, 5856.28940704,
       5876.28919216, 6893.9067899 , 2918.06782219, 5076.49486854,
       2462.17858407, 5644.55730985, 2354.26119294, 5895.81966584,
       3669.58755777, 3217.17750599, 6775.3371635 , 9041.857486  ,
       3006.13967322, 5954.59715035, 9831.39449959, 7239.43780184,
       3194.9725138 , 3903.85417053, 3065.2828397 , 9403.85892832,
       4265.09035862, 5957.40683564, 2577.62857482, 5808.88793633,
       3645.05884863, 3458.71212603, 4147.40953503, 5116.516754  ,
       6693.04660844, 4775.07785964, 4934.16299121, 8522.69667744,
       2947.63887253, 6589.59897834, 2825.12119967, 4128.20739265,
       5624.66296823, 2582.15753515, 4575.33760025, 5930.53518777,
       2545.30387589, 5332.63031502, 4511.00803813, 2511.93185543,
       6361.48603959, 2652.48933968, 7654.38229355, 3230.42224778,
       8500.95404804, 7153.79977323, 2949.26645157, 6618.00380937,
       2016.03157272, 2320.52386521, 3499.57448886, 2917.01875693,
       2833.81469366, 6587.33249828, 3339.0250826 , 4477.58092627,
       4666.36471264, 1932.29408337, 4814.97354078, 1932.24901912,
       2496.20781944, 5490.42568256, 5213.66152192, 5371.26319971,
       4967.89406373, 2845.87617479, 2886.75951022, 3556.86427353,
       5046.70771041, 2275.9877271 , 4683.32904359, 2994.57294746,
       3652.99695216, 2807.83677874, 9787.37151188, 5124.18539695,
       3343.99126161, 5832.80393337, 2829.46972555, 4362.05466865,
       1995.26002777, 5436.78122838, 3067.14548152, 3182.14439346,
       2941.64078359, 7662.63532139, 6096.52582755, 2356.98974336,
       7455.35601588, 3516.96859238, 6684.79945231, 8487.9084704 ,
       2970.42882347, 2737.86677058, 3474.24228182, 5640.27923143,
       3913.58626147, 6119.92705466, 6719.98864341, 3150.62522807,
       2952.9543295 , 1799.04938089, 3624.09551195, 5102.71222813,
       4660.34534098, 8884.71425134, 5876.28919216, 4724.00732312,
       5846.68364947, 3322.59766076, 4109.08765921, 3277.71428471,
       1824.84860509, 2888.02798753, 2437.93406396, 1526.96879679,
       4735.18217849, 2804.1375185 , 3233.47007768, 2068.57121784,
       6250.30413784, 6105.87608428, 2943.86886043, 4563.3128245 ,
       6109.27208668, 2829.75809886, 8886.91937649, 6545.83642325,
       1923.59703161, 4770.72933376, 4765.46967598, 2913.42917927,
       6844.12589917, 6940.31352656, 2600.82011598, 2647.41526869,
       2836.29170185, 5291.00191636, 6693.66078344, 5366.39011324,
       5188.66194384, 6445.66735999, 3386.18331703, 4056.99183493,
       3868.47163302])

In [36]:
from sklearn.metrics import mean_squared_error, r2_score
training_data_prediction=reg.predict(x_train)

In [37]:
r2_train=metrics.r2_score(y_train,training_data_prediction)

In [38]:
r2_train

0.39959368702324183

In [39]:
test_data_prediction=reg.predict(x_test)
r2_test=metrics.r2_score(y_test,test_data_prediction)
r2_test

0.36164702426392425

In [40]:
mse = mean_squared_error(y_train, training_data_prediction)
mse

NameError: name 'mean_absolute_error' is not defined

In [41]:
rmse = np.sqrt(mse)
rmse

2326.2052003517233

In [42]:
y_test

1325    2954
2216    4347
1264    4917
1314    2840
86      1898
        ...
2378    4195
2028    5430
2462    1921
1711    4232
1262    1845
Name: ElapsedTime(second), Length: 453, dtype: int64

In [44]:
mae=metrics.mean_absolute_error(y_test,test_data_prediction)

In [45]:
mae

1753.8435912130785

In [49]:
df=pd.read_csv('test.csv', encoding='latin-1')

In [50]:
df.isnull().sum()

ID                       0
DiagnosticICD10Code     95
SurgeryGroup             0
AnesthesiaType          95
SurgeryName            149
Age                      0
Sex                      0
Service                  0
DoctorID                 0
AnaesthetistID           0
dtype: int64

In [51]:
df= df.dropna(axis=0)

In [52]:
df.isnull().sum()

ID                     0
DiagnosticICD10Code    0
SurgeryGroup           0
AnesthesiaType         0
SurgeryName            0
Age                    0
Sex                    0
Service                0
DoctorID               0
AnaesthetistID         0
dtype: int64

In [53]:
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Certain infectious and parasitic diseases' if "'A" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Certain infectious and parasitic diseases' if "'B" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Neoplasms' if "'C" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Neoplasms' if "'D0"in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Neoplasms' if "'D1"in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Neoplasms' if "'D2"in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Neoplasms' if "'D3"in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Neoplasms' if "'D4"in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism' if "'D5" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism' if "'D6" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism' if "'D7" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism' if "'D8" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism' if "'D9" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Endocrine, nutritional and metabolic diseases' if "'E" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Mental, Behavioral and Neurodevelopmental disorders' if "'F" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Diseases of the nervous system' if "'G" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Diseases of the eye and adnexa' if "'H0" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Diseases of the eye and adnexa' if "'H1" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Diseases of the eye and adnexa' if "'H2" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Diseases of the eye and adnexa' if "'H3" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Diseases of the eye and adnexa' if "'H4" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Diseases of the eye and adnexa' if "'H5" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Diseases of the ear and mastoid process' if "'H6" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Diseases of the ear and mastoid process' if "'H7" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Diseases of the ear and mastoid process' if "'H8" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Diseases of the ear and mastoid process' if "'H9" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Diseases of the circulatory systems' if "'I" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Diseases of the respiratory system' if "'J" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Diseases of the digestive system' if "'K" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Diseases of the skin and subcutaneous tissue' if "'L" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Diseases of the musculoskeletal system and connective tissue' if "'M" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Diseases of the genitourinary system' if "'N" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Pregnancy, childbirth and the puerperium' if "'O" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Certain conditions originating in the perinatal period' if "'P" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Congenital malformations, deformations and chromosomal abnormalities' if "'Q" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Symptoms, signs and abnormal clinical and laboratory findings, not elsewhere classified' if "'R" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Injury, poisoning and certain other consequences of external causes' if "'S" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Injury, poisoning and certain other consequences of external causes' if "'T" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Codes for special purposes' if "'U" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'External causes of morbidity' if "'V" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'External causes of morbidity' if "'W" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'External causes of morbidity' if "'Y" in x else x)
df['DiagnosticICD10Code'] = df['DiagnosticICD10Code'].apply(lambda x: 'Factors influencing health status and contact with health services' if "'Z" in x else x)

In [54]:
df['SurgeryGroup'] = df['SurgeryGroup'].apply(lambda x: "4000" if "A1" in x else x)
df['SurgeryGroup'] = df['SurgeryGroup'].apply(lambda x: "2500" if "A2" in x else x)
df['SurgeryGroup'] = df['SurgeryGroup'].apply(lambda x: "1250" if "A3" in x else x)
df['SurgeryGroup'] = df['SurgeryGroup'].apply(lambda x: "750" if "B" in x else x)
df['SurgeryGroup'] = df['SurgeryGroup'].apply(lambda x: "400" if "C" in x else x)
df['SurgeryGroup'] = df['SurgeryGroup'].apply(lambda x: "200" if "D" in x else x)
df['SurgeryGroup'] = df['SurgeryGroup'].apply(lambda x: "100" if "E" in x else x)
df['SurgeryGroup'] = df['SurgeryGroup'].apply(lambda x: "0" if "{0}" in x else x)

In [55]:
df.head()

,ID,DiagnosticICD10Code,SurgeryGroup,AnesthesiaType,SurgeryName,Age,Sex,Service,DoctorID,AnaesthetistID
1,2091,Diseases of the skin and subcutaneous tissue,400,Spinal Anestezi,Pilonidal kist,41,MALE,GENEL CERRAH? SERV?S?,36,6
2,585,Diseases of the musculoskeletal system and con...,1250,Genel Anestezi,"Servikal disk bozukluklar?, radikülopati ile",59,FEMALE,ORTOPED? SERV?S?,42,14
3,1455,"Injury, poisoning and certain other consequenc...",750,Genel Anestezi,Humerus üst uç k?r???,54,FEMALE,ORTOPED? SERV?S?,23,14
4,1801,Diseases of the circulatory systems,100,Sedo Analjezi,Ülser veya enflamasyon olmadan alt ekstremiten...,50,MALE,KVC SERV?S?,46,13
5,1418,Diseases of the digestive system,400,Spinal Anestezi,"Bilateral inguinal herni, obstrüksiyonsuz veya...",31,MALE,GENEL CERRAH? SERV?S?,47,1

In [56]:
df["SurgeryGroup"]=df["SurgeryGroup"].astype("int64")

In [57]:
df["DiagnosticICD10Code"]=encoder.fit_transform(df["DiagnosticICD10Code"])
df["AnesthesiaType"]=encoder.fit_transform(df["AnesthesiaType"])
df["Sex"]=encoder.fit_transform(df["Sex"])
df["Service"]=encoder.fit_transform(df["Service"])
df["DoctorID"]=encoder.fit_transform(df["DoctorID"])
df["AnaesthetistID"]=encoder.fit_transform(df["AnaesthetistID"])

In [59]:
df.head()

,ID,DiagnosticICD10Code,SurgeryGroup,AnesthesiaType,SurgeryName,Age,Sex,Service,DoctorID,AnaesthetistID
1,2091,11,400,6,Pilonidal kist,41,1,0,28,5
2,585,8,1250,2,"Servikal disk bozukluklar?, radikülopati ile",59,0,7,33,12
3,1455,15,750,2,Humerus üst uç k?r???,54,0,7,16,12
4,1801,3,100,5,Ülser veya enflamasyon olmadan alt ekstremiten...,50,1,5,36,11
5,1418,4,400,6,"Bilateral inguinal herni, obstrüksiyonsuz veya...",31,1,0,37,0

In [61]:
test_df=df.drop(columns=["ID","SurgeryName"], axis=1)

In [62]:
test_df

,DiagnosticICD10Code,SurgeryGroup,AnesthesiaType,Age,Sex,Service,DoctorID,AnaesthetistID
1,11,400,6,41,1,0,28,5
2,8,1250,2,59,0,7,33,12
3,15,750,2,54,0,7,16,12
4,3,100,5,50,1,5,36,11
5,4,400,6,31,1,0,37,0
...,...,...,...,...,...,...,...,...
1110,4,400,2,66,0,0,28,3
1111,8,400,2,61,0,7,16,2
1112,7,200,5,4,1,9,6,3
1113,4,750,6,62,1,0,2,7
1114,4,750,2,58,1,0,2,12

In [63]:
reg.predict(test_df)

array([ 3328.36948568,  9679.43743225,  7658.44067896,  2490.79546207,
        2573.30532816,  4820.35797317,  3051.12040564,  2770.58218376,
        3211.35794898,  5373.57687547,  7511.24806083,  5070.79490253,
        5899.91683933,  5997.53662055,  3124.64552254,  5853.56466816,
        5645.42549362,  8354.17319391,  6671.22673591,  5022.96111786,
        4878.24358736,  4981.54754026,  5215.94636275,  2869.28554602,
        6813.55935237,  5169.02701595,  4329.99303859,  3570.96895258,
        4861.01260254,  4423.22814066,  4583.91593347,  2125.31412468,
        5840.55537347,  5727.05008043,  9430.21620588,  3351.77715479,
        2492.82286416,  4924.59551803,  2116.3702061 ,  4754.91890522,
        3246.75872534,  2186.193487  ,  5557.65974485,  2858.42133216,
        6037.53744159,  6429.96908586,  6106.09672   ,  5820.89109908,
        2010.08528971,  5864.79691747,  4999.05887679,  8571.86790069,
        3212.19001123,  8752.06897573,  4521.96188571,  2042.50265552,
        2929.00603274,  4804.06120651,  2801.23214471,  5393.72849439,
        3149.86804701,  5544.32581734,  4419.030123  ,  1930.23676194,
        4811.95503095,  4840.87681565,  6116.36673481,  4359.16539213,
        2124.87513883,  3134.86264219,  2964.553188  ,  4488.05786672,
        6090.68471952,  5646.61875726,  4521.20186084,  4557.5889144 ,
        6291.79524764,  3513.06326154,  2267.61242833,  8504.56369504,
        5953.61704635,  3442.29524668,  9343.63682779,  5782.43765588,
        6467.43805488,  2146.40748844,  2837.83747405,  3602.20260408,
        4855.24210306,  3579.81685522,  2987.56437559,  5818.81274407,
        5696.9505424 ,  6786.75337149,  8760.76602749, 13546.53242017,
        6836.5025839 ,  6338.84543631,  2451.76841173,  9211.66315494,
        4433.99039377,  3934.00371122,  4135.38002726,  1627.82972063,
        9457.4316401 ,  6637.96587607,  2954.76801251,  5477.35887692,
        2669.91682288,  2866.60877396,  3515.54951767,  3005.42897315,
        2199.23906464,  5974.48925433,  4078.63891103,  3341.19390755,
        3723.51469536,  8969.43262985,  5596.79647776,  2111.32012137,
        4935.89767561,  3671.36398218,  8460.5125783 ,  9513.43450059,
        2500.36114464,  2871.4950923 ,  7206.23946854,  6088.18263668,
        6896.94029231,  8659.59094668,  6407.29757145,  5781.7114094 ,
        3309.47222245,  3171.16071027,  6425.50452878,  2939.62090833,
        5602.59570601,  6315.27348533,  5168.89433062,  4718.26897584,
        4516.74933397,  5451.77722728,  2731.44545084,  2578.5977794 ,
        5185.79503146,  4754.60552438,  3703.43812954,  2481.72647868,
        5979.67191867,  4366.80535904,  4248.66392679,  4725.1551089 ,
        5395.14947305,  2886.67964954,  6063.51637497,  5255.08309567,
        6801.66386246,  4509.34954684,  4829.81973283,  2486.55661877,
        6245.11968289,  5529.32802784,  2253.04895423,  2965.7120636 ,
        4674.07224026,  2797.65410437,  4320.68106891,  2698.86679008,
        3045.61310848,  3530.89397291,  6451.05854771,  2107.27075552,
        2504.70967052,  5211.92246969,  9159.48084439,  6636.4386046 ,
        5034.94564159,  2731.44545084,  3466.31472076,  2610.99945917,
        3254.88003884,  3162.2925415 ,  2438.61315151,  3208.27580076,
        7027.23279387,  5778.59243011,  3221.32137839,  9473.90415015,
        2546.64020179,  3597.21095874,  3563.89445203,  3111.38096056,
        5919.55150458,  3678.08492818,  2496.01261876,  2098.97610258,
        2814.75109623,  2856.34965097,  8531.60688883,  3585.70537892,
        3633.10484819,  8883.40951452,  2846.70867384,  3240.55967404,
        2651.65408855,  4783.1836859 ,  2204.85862015,  9354.00945149,
        4626.9075039 ,  3063.29054794,  1953.55445327,  4245.0458094 ,
        3780.27565189,  4886.89800811,  3109.97236586,  4089.85488911,
        3031.80858261,  5661.73601609,  9419.83861243,  5112.42387624,
        7101.47831556,  4552.94741522,  3352.92588386,  3136.01585588,
        5421.04919625,  2234.7862199 ,  9080.44843032,  7254.95616944,
        9575.07281113,  4568.23241819,  5891.94245285,  2407.41452212,
        2652.52271936,  3124.64552254,  2952.77616855,  2793.84270961,
        4814.02671214,  6400.82779291,  2081.17960024,  3089.34770555,
        9609.86101817,  7182.50832006,  2422.20649048,  8582.0828489 ,
        2424.91830823,  6163.38186841,  3563.89445203,  4728.6183701 ,
        4885.49561618,  5801.2844632 ,  4592.29617138,  5984.02044455,
        9870.29816007,  5383.65151557,  5043.08929783,  3291.22242529,
        3592.84770315,  3049.96163436,  6502.16370408,  4441.30649755,
        9042.43597634,  3301.48387298,  9373.68536945,  4987.41396259,
        3211.10643018,  3307.85758058,  2233.47802962,  3535.3449804 ,
        6721.34681601,  3355.14557666,  7349.46496751,  4408.67506249,
        3247.41253367,  4353.63675363,  6109.93446969,  5545.68277155,
        3168.80149784,  6405.58658471,  6871.29079093,  6673.13380173,
        3106.38278821,  2907.11466228,  5450.29561378,  2789.31541213,
        4705.35892088,  6687.84324136,  5425.61887791,  5834.68895114,
        2125.06725786,  9287.08018256,  3155.33454197,  2855.48102015,
        1121.34068628,  3657.55945631,  3679.30208571,  4479.24624858,
        3126.70582143,  5590.93005543,  3054.31016024,  2735.39404934,
        6464.7572929 ,  1330.48881179,  3858.65133394,  9382.26968698,
        8957.33445447,  3213.13610802,  2212.03777545,  2853.88782915,
        6404.19910737,  5773.80958882,  2910.81392251,  5353.8690962 ,
        2902.7661364 ,  3569.07104226,  4762.76883099,  2819.93386489,
        2742.1699047 ,  2368.27778921,  3980.65721587,  3116.38329477,
        6778.70426458,  4827.40724783,  5166.16036621,  4801.41108367,
        3493.19307181,  6605.82528398,  6871.82452655,  4820.92270378,
        4594.78041602,  3485.65850494,  3506.67378349,  9977.56674249,
        3706.74278289,  4910.87378932,  4899.17499113,  2537.94315003,
        4098.96712102,  6816.24109237,  3823.00196246,  3074.41877299,
        3014.30479651,  4899.27891404,  5636.62720246,  3833.48349539,
        5236.45944556,  2948.42764267,  4941.9013017 ,  6678.19415109,
        3227.69958212,  5443.35884225,  3895.06649891,  4359.44519236,
        2448.17883408,  3822.00766045,  6032.32482759,  5957.206624  ,
        4607.36915111,  4615.86456273,  2494.4947223 ,  2964.95311538,
        3277.16157543,  9613.45059582,  5702.67899533,  3262.37100241,
        3566.32223247,  3588.50609795,  2866.9986523 ,  3547.85146858,
        4068.12576858,  6005.53019992,  6954.43276245,  4650.34490427,
        2429.15715152,  5415.18277392,  2809.92919647,  3232.048108  ,
        9538.76670764,  4918.64530593,  2231.19664225,  4951.86680733,
        6577.4559387 ,  6504.39508687,  4020.74102902,  4584.86757349,
        2089.00802119,  4704.55461692,  5321.28874914,  3172.29433008,
        3187.80390097,  4173.98003861,  5480.62382174,  3302.84603325,
        2621.21440739,  4088.14796049,  5197.793311  ,  3280.6408409 ,
        6660.36973882,  6432.43668821,  3568.41723393,  3173.15841821,
        3421.0209399 ,  5935.89831   ,  4842.21647189,  5293.42404929,
        6884.02957646,  2176.14818651,  2645.02384571,  4343.87742707,
        3198.88588219,  1901.07298268,  4963.05609987,  4336.38152148,
        6807.54893463,  2935.16080494,  3131.60341775,  5143.43929566,
        6582.16749165,  6328.31906297,  3961.40248316,  2553.70222648,
        2777.13392262,  4144.9948702 ,  6775.48312904,  3476.23410233,
        4444.25718822,  6066.43477273,  4710.22285258,  4094.15158658,
        6359.46378677,  3108.4808613 ,  3030.9399518 ,  6529.79216905,
        3207.18767702,  4854.17183588,  6618.68175373,  2390.13010119,
        4815.99846236,  2741.26047168,  2639.47714172,  3362.0972429 ,
        6756.47225318,  4174.16324858,  9247.96925844,  2845.19077739,
        5364.51835982,  6832.33680769,  5934.59357318,  2858.63161196,
        2023.59065554,  3025.02925037,  3194.21739393,  6025.18107877,
        2894.97677393,  7212.1483551 ,  2186.193487  ,  5360.49501487,
        4067.42334458,  6454.18395386,  6154.83541844,  5672.17212008,
        2992.59402394,  2763.91253409,  2487.315567  ,  5742.28632661,
        5456.12575316,  3704.17091118,  2580.15250693,  4851.79099019,
        2426.07707951,  4898.07004734,  3734.91209253,  6686.62627288,
        6520.92510226,  6048.80229908,  8974.41428979,  6295.78189561,
        6221.91959173,  5939.26673188,  2781.74457408,  3810.71533305,
        5742.28632661,  3064.16598328,  6208.42280469,  4798.61534377,
        4970.01985907,  6438.45373661,  3039.63700356,  4912.73007441,
        3131.66733   ,  5944.16104636,  5178.9997554 ,  4250.75034666,
        5993.47644454,  2753.18808024,  2713.65141995,  4875.66502269,
        5874.25999946,  7193.70219457,  2328.49179065,  2429.26683411,
        4704.55461692,  6361.81118544,  4959.93712058,  3390.22957637,
        2582.58718011,  3861.69512299,  3636.05360897,  3789.50153178,
        5356.90543722,  6787.01369902,  3181.42569725,  5172.53917402,
        5260.19056977,  5786.53053364,  4470.3483435 ,  5029.07921925,
        8890.27440162,  5496.05771726,  2402.81655366,  7458.39980493,
        3189.14264501,  6000.0245656 ,  5934.22272975,  6672.98578425,
        5798.51351371,  4658.08600391,  7433.60485568,  2342.29631651,
        3022.24290004,  6916.97657123,  5409.32958344,  2169.66801429,
        5816.05855252,  4922.09960469,  6567.1122393 ,  4313.92006253,
        5900.57454816,  2774.93070964,  5416.98902024,  3168.13078134,
        4557.16035866,  5259.20285885,  3144.71290764,  3331.21485185,
        6186.6801753 ,  3116.34829384,  6729.25618937,  6791.8608456 ,
        3163.02330723,  6365.06237445,  3739.26061841,  4073.23324269,
        5838.21319151,  3527.86980566,  2541.4230451 ,  2270.44305775,
        2730.61120806,  2872.11617544,  3094.99520858,  2790.83330859,
        4682.81198752,  2835.3710861 ,  8965.71723803,  5275.27099754,
        5963.03676338,  6787.99488579,  5521.35364135,  6265.12901973,
        3161.42212008,  1539.57717919,  3852.44000928,  5581.39886521,
        2840.84225151,  6654.29820897,  8615.746777  ,  5850.39951335,
        5847.69824582,  5252.26046238,  8517.9650082 ,  2823.84340492,
        3246.17195313,  5211.06228206,  7602.56710431,  5761.48667646,
        3136.82246937,  2230.54737661,  9411.14653042,  7118.52665815,
        5622.81244281,  3547.32841287,  6839.86694893,  9368.57789534,
        3021.48395181,  1677.41727438,  1906.87943988,  3198.5704625 ,
        4947.51828145,  7242.4815909 ,  3022.35258262,  6152.61810521,
        5182.06311817,  5213.60987641,  2884.86696561,  3106.38278821,
        4972.9366852 ,  6097.24906645,  7706.89123836,  2740.50152345,
        2138.11283549,  2749.95752344,  3150.22706786,  6280.43137271,
        3155.52002769,  5386.51663734,  5266.38962107,  7461.33364661,
        2744.49102848,  5516.71676561,  3884.21195952,  5126.22840211,
        3207.04625417,  2437.85420328,  3285.45192973,  2748.8693997 ,
        3659.16775593,  4634.97820285,  2593.55815646,  4925.811935  ,
        3137.36697594,  5459.24265624,  6357.01224387,  5250.73456979,
        4701.6642656 ,  6200.80994721,  6227.53081181,  6030.0380434 ,
       10036.12874176,  3144.71290764,  9851.79938119,  6234.51395997,
        4964.91238497,  3832.84852853,  5525.70216723,  3348.57735799,
        5583.67570989,  6107.80307048,  7026.44866645,  2989.66423928,
        2837.83747405,  4919.39972407,  6563.96971236,  2613.31313493,
        5849.97509051,  6629.79450847,  5160.86091354,  2894.97677393,
        6205.74748452,  4844.92323585,  7041.03794934,  3613.838305  ,
        3371.11544915,  9523.25583129,  5743.33362471,  7058.11238978,
        2973.65016713,  9324.33368831,  3047.56505805,  4056.27345457,
        3165.48553331,  3729.16990188,  4556.21640986,  9403.36610238,
        3212.62432664,  6825.36367348,  5383.80089646,  8274.81288965,
        2588.08606778,  2929.0487811 ,  6275.59006436,  2139.06275925,
        4997.33480127,  3023.00184827,  5861.21442182,  9688.13448401,
        3223.06043063,  4617.58409933,  2458.89784959,  2757.53660612,
        3536.18074554,  3140.36438176,  5653.3273142 ,  4068.12576858,
        5202.74671726,  6167.48474374,  3585.24281597,  3199.68388889,
        4640.13103269,  6474.0433561 ,  3207.08253712,  5364.38615009,
        4980.29450778,  5887.59392697,  2372.62631509,  4377.08797116,
        3491.75723999,  5061.89953313,  5792.28691698,  9079.6894821 ,
        7695.35487363,  3267.96189944,  2793.84270961,  3387.74568828,
        4178.79112743,  6520.27992476,  3337.93062557,  5922.41841696,
        4573.56378151,  5453.57379047,  5363.28881323,  2611.86808999,
        9371.24587953,  2987.15990553,  4064.27200369,  3101.2753141 ,
        2200.10769545,  2947.55901186,  4034.37811113,  6486.60570298,
        5508.01971385,  6041.45165207,  5720.10938181,  9502.42284738,
        6779.3955489 ,  2938.56717262,  6148.64344915,  5016.58518988,
        8902.6868452 ,  2877.22364955,  5328.46224702,  3151.7172904 ,
        4014.53709237,  1798.81824917,  4296.83765379,  5950.36495659,
        8549.79035182,  7064.76557058,  8891.79229808,  2277.06842832,
        7145.45308485,  6727.9313456 ,  5310.45668878,  6701.45351972,
        4676.91683266,  5982.16291536,  5015.06096013,  3351.23136619,
        6627.38380654,  5835.44789937,  2407.41452212,  3212.29515113,
        3989.23190313,  4921.42712617,  2620.56514174,  7147.38756229,
        2728.21489404,  3534.29931757,  6212.2574371 ,  2584.55112489,
        1989.86055677,  3115.76349365,  4357.62285221,  3004.55400905,
        6699.42143694,  3054.84784838,  9509.24861995,  2880.7016497 ,
        6302.22790769,  3259.09136098,  5809.35674409,  3045.61310848,
        4106.4900444 ,  5307.79559175,  3356.99322629,  3595.75279121,
        3934.00371122,  6780.68018129,  3901.60606304,  5125.13861552,
        2911.46318816,  5169.09268207,  4884.02368581,  4117.98592374,
        9001.41601626,  2537.94315003,  6622.05334645,  3900.54457293,
        6921.3509059 ,  2625.56293327,  4166.86599302,  6466.47058327,
        5509.79325843,  6381.69752974,  5836.17056464,  7333.37560081,
        2660.27584576,  3244.00844174,  6419.19306136,  3509.8282271 ,
        3607.73635818,  6656.30335219,  3846.1691055 ,  7176.32708141,
        5975.03504292,  3485.00800351,  4435.80149217,  4367.86244389,
        2753.18808024,  5988.83956879,  1991.9922031 ,  9432.01492966,
        5358.21762207,  5977.41784808,  6587.04235781,  3004.77350197,
        4331.80395729,  6315.30605327,  5039.26933528,  5510.86357513,
        5356.90543722,  3279.555597  ,  5963.46118622,  4091.06248025,
        3096.92678822,  9196.15227859,  4417.40708472,  3129.34852659,
        6177.8552948 ,  3549.91515363,  3517.19862779,  5862.95347405,
        5859.47536959,  2842.14065504,  5745.44158886,  7153.99317685,
        5719.23896039,  3167.06599823,  3573.63990528,  2336.42989418,
        5855.59788911,  4472.41270134,  4814.48355469,  2191.41064369,
        4537.79273704,  3990.15049698,  5311.93856492,  2103.32462846,
        3251.47963752,  3146.82297593,  5394.52372557,  6470.81910915,
        2085.52812612,  3542.29778818,  2294.10340666,  5750.45225973,
        5046.90763818,  6066.77035025,  4042.46892871,  2195.75916957,
        3196.21032712,  4493.19041481,  5368.90371677,  9613.45059582,
        2643.8256676 ,  2107.92002116,  5038.04154562,  6818.71891016,
        2912.12153917,  3783.51995375,  2328.49179065,  8655.24884063,
        3936.31907984,  3590.81367166,  8557.95164386,  4686.65100776,
        5371.69751512,  1970.2495737 ,  3022.35258262,  3181.93530721,
        4347.80661425,  5470.14025013,  9417.17062824,  2819.17491666,
        2534.16859524,  2609.53407983,  5786.05993528,  3445.10901547,
        6701.35952817,  8727.1158552 , 10595.81497209,  5872.40947404,
        2494.4947223 ,  8461.27152653,  3110.84099667,  2996.69625133,
        5261.17067378,  4893.95949729,  3532.52904625,  4756.8691372 ,
        2687.3109264 ,  7113.40250434,  6005.02689981,  2907.11466228,
        3342.27915145,  7001.14226819,  2758.40523693,  5800.65969233,
        3909.09459226,  2727.12677031,  6401.99700705,  2690.16973832,
        3640.68840851,  5289.4369873 ,  5525.19266159,  2991.80321888,
        4796.01162979,  3054.1251831 ,  9635.301434  ,  4451.48824302,
        5101.35181671,  5964.76881184,  8485.36155459,  4778.1774512 ,
        6586.61133108,  6088.86526172,  4083.18706514,  4941.57666888,
        5030.4780356 ,  6231.24962836,  6987.33774232,  2078.34897082,
        3487.37063839,  2771.45081457,  3247.08335816,  6798.07457388,
        3198.97028555,  6996.79374231,  2374.91281876,  6469.69483022,
        5016.90513967,  6344.07872458,  2080.31096943,  6475.92658326,
        4487.95272682,  6171.22544325,  4454.46816651,  2424.80862564,
        5519.76055466,  2711.73022354,  5075.14342841,  8662.82161345,
        3289.33789266,  6582.80701749,  2301.70165228,  5004.04911788,
        3590.78207428,  9717.81521694,  2138.35970232,  8760.29542913,
        3738.20016999,  2752.53881459,  3589.12591577,  3202.0026923 ,
        6303.13971819,  2222.73609887,  3837.88304887,  5003.75608498,
        3197.65416642,  4832.17976389,  5430.83037718])